version: "3.9"

services:
  backend:
    build: ./backend
    container_name: app-backend
    ports:
      - "3175:3175"
    restart: always

  frontend:
    build: ./frontend
    container_name: app-frontend
    ports:
      - "5175:5175"
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:latest
    container_name: react-nginx1
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always

  
