version: "3.9"

services:
  backend:
    build: ./backend
    container_name: react-backend
    ports:
      - "3175:3175"
    restart: always

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5175:5175"
    depends_on:
      - backend
    restart: always
